spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cocplatform?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.example
logging:
  level:
    root: info
    web: debug
    sql: debug
